#!/bin/sh
DIRECTORY=$HOME/bin
echo "Compiling into local bin folder"
if [ -d "$DIRECTORY" ]; then
	echo "Local bin exists"
else
	echo "Creating bin folder"
	echo "Restart the shell later to activate local bin folder"
	mkdir $DIRECTORY
fi
echo "Compiling"
gcc -Wall chat_core.c chat_connect.c -o $HOME/bin/chat-connect -lpthread -I encryption/
gcc -Wall chat_core.c chat_host.c -o $HOME/bin/chat-host -lpthread -I encryption/
echo "Out:"
echo "$HOME/bin/chat-host"
echo "$HOME/bin/chat-connect"
